export const data = [
    {title: "Simulador de asteróides", description: "A simulação tem como base estudos sobre impactos de asteroides de Gareth Collins, professor de Ciências Planetárias do Imperial College London, na Inglaterra, e Clemens Rumpf, engenheiro aeroespacial da Nasa.",image: "https://cdn.universoracionalista.org/wp-content/uploads/2022/12/simulador-impacto-asteroides-sao-paulo.jpg", link: "https://neal.fun/asteroid-launcher"},
    {title: "Telescópio Webb", description: "Imagens fantásticas do supertelescópio James Webb mostram o Universo como nunca antes visto. Foi um presente de US$ 10 bilhões para o mundo. Uma máquina que mostraria nosso lugar no Universo.",image: "https://pbs.twimg.com/tweet_video_thumb/F0Smm7tWIAg2HBE.jpg", link: "https://webbtelescope.org/images"},
    {title: "Dia do planeta vermelho | 28 de novembro", description: "O Dia do Planeta Vermelho comemora-se a 28 de novembro. Este dia celebra o lançamento da nave espacial Mariner 4, responsável pela receção e pelo envio das primeiras fotografias da superfície marciana para a Terra, a 28 de novembro de 1964.",image: "https://static.vecteezy.com/ti/vetor-gratis/p1/4508038-vector-graphic-of-red-planet-day-good-for-red-planet-day-celebration-flat-design-flyer-design-flat-illustration-vetor.jpg", link: "https://www.calendarr.com/portugal/dia-do-planeta-vermelho/"},
    {title: "Alguns de nossos planetas em libras", description: "Partipando do Drops Marcílio nos conta mais sobre os planetas do nosso sistema solar em libras.",image: "https://lh3.googleusercontent.com/u/1/drive-viewer/AITFw-xGdfLOsb2X6qzDQpUykxIVQp5kDmS3T0ILAtJFpqGoyDBe9oB6v6o5r0c2hggs9t6v71TF9SBwwNZ1JaJ-ExlriNReVw=w1920-h1080-k-pd", link: "https://drive.google.com/file/d/1xsCDAfFG6khh2QZRJg-PRPK9_pEZNuqN/view"},
    {title: "Conheça Bingo", description: "BINGO é um radiotelescópio projetado para fazer a primeira detecção de Oscilações Acústicas de Bárions, que são ondas geradas pela interação dos átomos com a radiação no inicio do Universo, e que podem ser observadas na faixa de radiofrequência.",image: "https://bingotelescope.org/wp-content/uploads/2021/07/3-1536x513.png", link: "https://www.youtube.com/live/gsZPfk65Yt8?feature=share"},
    {title: "Sistema solar interativo", description: "O Eyes on the Solar System incorpora informações de orientação vindas diretamente da base de dados da NASA. Ou seja, se você quer ver como um determinado satélite chegou até as luas de Saturno, você pode.",image: "https://www.thewindowsclub.com/wp-content/uploads/2017/09/Nasas-Eyes.jpg", link: "https://eyes.nasa.gov/apps/orrery/#/home"},
    {title: "Curiodidade sobre a água", description: "Imagens fantásticas do supertelescópio James Webb mostram o Universo como nunca antes visto. Foi um presente de US$ 10 bilhões para o mundo. Uma máquina que mostraria nosso lugar no Universo.",image: "https://www.aguasustentavel.org.br/images/blog/drop-of-water-578897_1280.jpg", link: "https://www.youtube.com/watch?v=OY3L1DPgxjA&feature=youtu.be"},
    {title: "A velocidade da luz", description: "Imagens fantásticas do supertelescópio James Webb mostram o Universo como nunca antes visto. Foi um presente de US$ 10 bilhões para o mundo. Uma máquina que mostraria nosso lugar no Universo.",image: "https://g3i5r4x7.rocketcdn.me/wp-content/uploads/2020/08/velocidade-da-luz-o-que-e-definicao-caracteristicas-e-como-se-calcula.jpg", link: "https://www.youtube.com/watch?v=C_jt0FiQE3s&feature=youtu.bes"},
    {title: "Google Sky Maps", description: "Imagens fantásticas do supertelescópio James Webb mostram o Universo como nunca antes visto. Foi um presente de US$ 10 bilhões para o mundo. Uma máquina que mostraria nosso lugar no Universo.",image: "https://innovatorbrasil.com.br/wp-content/uploads/2015/12/Google-SM-banner-550x269.jpg", link: "https://www.google.com/sky/"},
];
