import mercurio from "../assets/mercurio.png";
import venus from "../assets/venus.png";
import terra from "../assets/terra.png";
import marte from "../assets/marte.png";
import jupiter from "../assets/jupiter.png";
import saturno from "../assets/saturno.png";
import urano from "../assets/urano.png";
import netuno from "../assets/netuno.png";

import mercurioStructure from "../assets/structure/mercurio.png";
import venusStructure from "../assets/structure/venus.png";
import terraStructure from "../assets/structure/terra.png";
import marteStructure from "../assets/structure/marte.png";
import jupiterStructure from "../assets/structure/jupiter.png";
import saturnoStructure from "../assets/structure/saturno.png";
import uranoStructure from "../assets/structure/urano.png";
import netunoStructure from "../assets/structure/netuno.png";

import mercurioInternal from "../assets/internal/mercurio.png";
import venusInternal from "../assets/internal/venus.png";
import terraInternal from "../assets/internal/terra.png";
import marteInternal from "../assets/internal/marte.png";
import jupiterInternal from "../assets/internal/jupiter.png";
import saturnoInternal from "../assets/internal/saturno.png";
import uranoInternal from "../assets/internal/urano.png";
import netunoInternal from "../assets/internal/netuno.png";

export const planets = [
    {planetName: "Mercúrio", imagePrincipal: mercurio, imageStructure: mercurioStructure, imageInternal: mercurioInternal, rotacao: "58.6", revolucao: "87.97", raio: "2,439.7", temperatura: "430", infoPlanet: "Mercúrio é o menor planeta do Sistema Solar e o mais próximo do Sol. Sua órbita ao redor do Sol leva 87,97 dias terrestres, o menor de todos os planetas do Sol. Mercúrio é um dos quatro planetas terrestres do Sistema Solar e é um corpo rochoso como a Terra.", structure: "Mercúrio parece ter uma crosta sólida de silicato e um manto sobrejacente a uma camada de núcleo externo sólida de sulfeto de ferro, uma camada de núcleo líquido mais profunda e um núcleo interno sólido. A densidade do planeta é a segunda mais alta do Sistema Solar, com 5,427 g/cm3, apenas um pouco menor que a densidade da Terra.", geology: "A superfície de Mercúrio é semelhante em aparência à da Lua, mostrando extensas planícies semelhantes a mares e crateras pesadas, indicando que está geologicamente inativo há bilhões de anos. É mais heterogêneo do que o de Marte ou o da Lua."},
    {planetName: "Vênus", imagePrincipal: venus, imageStructure: venusStructure, imageInternal: venusInternal, rotacao: "243", revolucao: "224.7", raio: "6,051.8", temperatura: "471", infoPlanet: "Vênus é o segundo planeta a partir do Sol. É nomeado após a deusa romana do amor e da beleza. Como o objeto natural mais brilhante no céu noturno da Terra depois da Lua, Vênus pode lançar sombras e pode ser, em raras ocasiões, visível a olho nu em plena luz do dia.", structure: "A semelhança em tamanho e densidade entre Vênus e a Terra sugere que eles compartilham uma estrutura interna semelhante: um núcleo, manto e crosta. Como o da Terra, o núcleo venusiano é provavelmente pelo menos parcialmente líquido porque os dois planetas estão esfriando aproximadamente na mesma taxa.", geology: "Grande parte da superfície venusiana parece ter sido moldada pela atividade vulcânica. Vênus tem várias vezes mais vulcões que a Terra e tem 167 grandes vulcões com mais de 100 km (60 milhas) de diâmetro. O único complexo vulcânico deste tamanho na Terra é a Grande Ilha do Havaí."},
    {planetName: "Terra", imagePrincipal: terra, imageStructure: terraStructure, imageInternal: terraInternal, rotacao: "0.99", revolucao: "365.26", raio: "6,371", temperatura: "16", infoPlanet: "Terceiro planeta a partir do Sol e o único planeta conhecido a abrigar vida. Cerca de 29,2% da superfície da Terra é terra, com os restantes 70,8% cobertos por água. A distância da Terra ao Sol, as propriedades físicas e a história geológica permitiram que a vida evoluísse e prosperasse.", structure: "O interior da Terra, como o de outros planetas terrestres, é dividido em camadas por suas propriedades químicas ou físicas (reológicas). A camada externa é uma crosta sólida de silicato quimicamente distinta, que é sustentada por um manto sólido altamente viscoso.", geology: "A superfície total da Terra é de cerca de 510 milhões de km2. A crosta continental é constituída por material de menor densidade como as rochas ígneas granito e andesito. Menos comum é o basalto, uma rocha vulcânica mais densa que é o principal constituinte dos fundos oceânicos."},
    {planetName: "Marte", imagePrincipal: marte, imageStructure: marteStructure, imageInternal: marteInternal, rotacao: "1.03", revolucao: "1.88", raio: "3,389.5", temperatura: "-28",  infoPlanet: "Marte é o quarto planeta a partir do Sol e o segundo menor planeta do Sistema Solar, sendo maior do que apenas Mercúrio. Em inglês, Marte carrega o nome do deus romano da guerra e é muitas vezes referido como o 'Planeta Vermelho'.", structure: "Como a Terra, Marte se diferenciou em um núcleo metálico denso sobreposto por materiais menos densos. Os cientistas determinaram inicialmente que o núcleo é pelo menos parcialmente líquido. Os modelos atuais de seu interior implicam um núcleo consistindo principalmente de ferro e níquel com cerca de 16 a 17% de enxofre.", geology: "Marte é um planeta terrestre cuja superfície consiste em minerais contendo silício e oxigênio, metais e outros elementos que normalmente compõem a rocha. A superfície é composta principalmente de basalto toleítico, embora partes sejam mais ricas em sílica do que o basalto típico."},
    {planetName: "Júpiter", imagePrincipal: jupiter, imageStructure: jupiterStructure, imageInternal: jupiterInternal, rotacao: "9.93", revolucao: "11.86", raio: "69,911", temperatura: "-108", infoPlanet: "Júpiter é o quinto planeta a partir do Sol e o maior do Sistema Solar. É um gigante gasoso com uma massa duas vezes e meia maior que a de todos os outros planetas do Sistema Solar combinados, mas menos de um milésimo da massa do Sol.", structure: "Quando o Juno chegou em 2016, descobriu que Júpiter tem um núcleo muito difuso que se mistura ao seu manto. Uma possível causa é um impacto de um planeta de cerca de dez massas terrestres alguns milhões de anos após a formação de Júpiter, o que teria interrompido um núcleo joviano originalmente sólido.", geology: "A característica mais conhecida de Júpiter é a Grande Mancha Vermelha, uma persistente tempestade anticiclônica localizada 22° ao sul do equador. Sabe-se que existe desde pelo menos 1831, e possivelmente desde 1665."},
    {planetName: "Saturno", imagePrincipal: saturno, imageStructure: saturnoStructure, imageInternal: saturnoInternal, rotacao: "10.8", revolucao: "29.46", raio: "58,232", temperatura: "-138", infoPlanet: "Saturno é o sexto planeta a partir do Sol e o segundo maior do Sistema Solar, depois de Júpiter. É um gigante gasoso com um raio médio de cerca de nove vezes e meia o da Terra. Tem apenas um oitavo da densidade média da Terra.", structure: "Apesar de consistir principalmente de hidrogênio e hélio, a maior parte da massa de Saturno não está na fase gasosa, porque o hidrogênio se torna um líquido não ideal quando a densidade é superior a 0,01 g/cm3, que é alcançada em um raio contendo 99,9% da massa de Saturno.", geology: "A atmosfera externa de Saturno contém 96,3% de hidrogênio molecular e 3,25% de hélio em volume. A característica mais famosa do planeta é o seu proeminente sistema de anéis, que é composto principalmente de partículas de gelo com uma quantidade menor de detritos rochosos e poeira."},
    {planetName: "Urano", imagePrincipal: urano, imageStructure: uranoStructure, imageInternal: uranoInternal, rotacao: "17.2", revolucao: "84", raio: "25,362", temperatura: "-195", infoPlanet: "Urano é o sétimo planeta a partir do Sol. Seu nome é uma referência ao deus grego do céu, Urano segundo a mitologia grega, era o bisavô de Ares. Tem o terceiro maior raio planetário e a quarta maior massa planetária do Sistema Solar.", structure: "", geology: "A composição da atmosfera de Urano é diferente de seu volume, consistindo principalmente de hidrogênio molecular e hélio. A fração molar de hélio, ou seja, o número de átomos de hélio por molécula de gás, é 0,15±0,03 na troposfera superior."},
    {planetName: "Netuno", imagePrincipal: netuno, imageStructure: netunoStructure, imageInternal: netunoInternal, rotacao: "16.08", revolucao: "164.79", raio: "24,622", temperatura: "-201", infoPlanet: "Netuno é o oitavo e mais distante planeta solar conhecido do Sol. No Sistema Solar, é o quarto maior planeta em diâmetro, o terceiro planeta mais massivo e o planeta gigante mais denso. É 17 vezes a massa da Terra, mais massiva que seu quase gêmeo Urano.", structure: "A estrutura interna de Netuno se assemelha à de Urano. Sua atmosfera forma cerca de 5% a 10% de sua massa e se estende talvez de 10% a 20% do caminho em direção ao núcleo. Concentrações crescentes de metano, amônia e água são encontradas nas regiões mais baixas.", geology: "A atmosfera de Netuno é 80% de hidrogênio e 19% de hélio. Uma pequena quantidade de metano também está presente. Bandas de absorção proeminentes de metano existem em comprimentos de onda acima de 600 nm, na porção vermelha e infravermelha do espectro."}
];
